export const DEFAULT_API_BASE_URL = 'https://applauseone.com/applauseoneapi'

export const API_BASE_URL = (import.meta.env.VITE_API_BASE_URL || DEFAULT_API_BASE_URL).replace(/\/$/, '')

/**
 * Production Client origin (SPA).
 * Activation links are generated by ApplauseOneAPI (`activation_link()` in helpers.php).
 * When API `frontend_activation_url` is empty, emails use `{API}/auth/activate?token=...`.
 * To open this Client instead, backend config must set (backend-only change):
 * frontend_activation_url = https://applause-one-client-ui.vercel.app/verify-email?token={token}
 */
export const DEFAULT_CLIENT_APP_URL = 'https://applause-one-client-ui.vercel.app'

export const CLIENT_APP_URL = (
  import.meta.env.VITE_CLIENT_BASE_URL ||
  (typeof window !== 'undefined' ? window.location.origin : DEFAULT_CLIENT_APP_URL)
).replace(/\/$/, '')

export function clientVerifyEmailUrl(token: string) {
  return `${CLIENT_APP_URL}/verify-email?token=${encodeURIComponent(token)}`
}
