export const paths = {
  home: '/',
  howItWorks: '/how-it-works',
  rewards: '/rewards',
  redeemRewards: '/redeem-rewards',
  help: '/help',
  about: '/about',
  contact: '/contact',
  privacyPolicy: '/privacy-policy',
  termsConditions: '/terms-conditions',
  join: '/join',
  login: '/login',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  verifyEmail: '/verify-email',
  dashboard: '/dashboard',
  history: '/history',
  settings: '/settings',
  surveys: '/surveys',
} as const

export const legacyPanelistRedirects: Record<string, string> = {
  '/panelist': paths.dashboard,
  '/panelist/dashboard': paths.dashboard,
  '/panelist/rewards': paths.rewards,
  '/panelist/redeem-rewards': paths.redeemRewards,
  '/panelist/reward-requests': paths.history,
  '/panelist/reward-history': paths.history,
  '/panelist/profile': paths.settings,
  '/panelist/projects': paths.surveys,
}
